[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/claude"
  to = "/.netlify/functions/claude"
  status = 200

[[redirects]]
  from = "/api/kroger"
  to = "/.netlify/functions/kroger"
  status = 200

[[redirects]]
  from = "/kroger-callback"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200
